// Package conformance holds the input case suite, the output goldens and the
// tests that run over the whole case suite: golden comparison, and the
// invariants every diagram must satisfy.
//
// Goldens are generated by flowcast itself with go test ./conformance -update.
// Changing a golden requires looking at the image and reading the diff: a golden
// that changes silently is a behavior change nobody reviewed.
package conformance

// Dir returns the case suite directory, relative to this package.
func Dir() string { return "." }
