#!/bin/sh
# Records the non-path arguments in the output file, so the CLI transcripts also
# pin what the tool passes to drawio, such as the PNG scale. Paths are not
# recorded because the temp directory differs between runs.
fmt=''
out=''
scale=''
flags=''
prev=''
for arg in "$@"; do
	case "$prev" in
	-f) fmt="$arg" ;;
	-o) out="$arg" ;;
	-s) scale="$arg" ;;
	*)
		case "$arg" in
		-*) flags="$flags $arg" ;;
		esac
		;;
	esac
	prev="$arg"
done
if [ "$fmt" = svg ]; then
	printf '<svg xmlns="http://www.w3.org/2000/svg"><g /></svg>' > "$out"
else
	printf 'fake PNG: format %s, scale "%s", flags%s\n' "$fmt" "$scale" "$flags" > "$out"
fi
